title: Gabriel Gomes XP
description: >-
  Documentando minha jornada de aprendizado em tecnologia e programação.
theme: minima
permalink: /:title/

# Configuração do Menu Superior
header_pages:
  - index.md
  - blog.md

# Configurações de Redes Sociais (Opcional)
minima:
  social_links:
    - { platform: github, user_name: gabrielgomesxp }
